### ISSUE TITLE
Purifier/Fan Speed/Mode not implemented correctly

### ISSUE THREAD

**Issue by panhans** [AnthonMS/my-cards#13]
Hi there,

using the card with my Xiaomi Purifier 3H.
I have noticed when changing the slider the mode of the purifier will set to mode _fan_ instead of _Favorite_.
With mode _fan_ the purifier provides only 3 different fanspeed presets. (33% / 66% / 100% ) and cant be adjusted stepless as assumed.
Didnt' found card options that could handle that behavior.

Greetings!

**Comment by AnthonMS** [comment]
If you can share some more information about the following, I will be able to implement that fan the next time I'm working on the card.
1. What kind of entity is it?
2. Which services can be called?
3. What is it you want? I mean, the fan mode only provides the three steps, but does the Favorite mode provide stepless?

**Comment by AnthonMS** [comment]
I'm pretty sure this has been resolved. If not let me know. I might update the old slider as well to fix it.

**Comment by panhans** [comment]
Oh, sry! I completly missed that!

1. It's a fan entity
2.
Service for setting mode

```
service: fan.set_preset_mode
data:
  preset_mode: Favorite
target:
  entity_id: fan.xiaomi_air_purifier_3h
```

Service for setting Fanspeed
```
service: fan.set_percentage
data:
  percentage: 44
target:
  entity_id: fan.xiaomi_air_purifier_3h
```

3. Exactly: preset mode _Fan_ provides 4 steps and preset mode Favorite let you set the speed stepless.

**Comment by AnthonMS** [comment]
Sorry for the long wait on this one! It's implemented in v2.3.0-beta.2, out now.

There's a new presetMode key. Set it to the preset your purifier needs for stepless speed (Favorite on the 3H), and the card switches the fan into that preset before writing the percentage, so set_percentage no longer knocks it back into the stepped Fan preset:

```yaml
type: custom:my-slider-v2
entity: fan.xiaomi_air_purifier_3h
presetMode: Favorite
```

How it works: if the fan isn't already in that preset, the card calls fan.set_preset_mode and then fan.set_percentage (chained, so the preset switch lands first). If it's already in the preset, it just sets the percentage. Without the key, fan sliders behave exactly as before.

One honest heads-up: I don't own a preset fan or purifier, so I couldn't test this against real hardware. The logic is covered by tests, but I'd really appreciate you trying it on your 3H and letting me know if it does the right thing. If the preset it needs isn't called "Favorite", that's the value to put in presetMode (and if you set a name the fan doesn't have, the card just sets the percentage and logs a warning).

If I don't hear back before releasing the next stable version in about 2 weeks time, I will close this issue as completed.
