### ISSUE TITLE
Value from current Slider position

### ISSUE THREAD

**Issue by huskydrive** [AnthonMS/my-cards#23]
Hi,
First of all very great work.
I have only a question is it possible that i can show the value from the slider while dragging, so i can as example drag it to 52% ?

Thanks.

**Comment by AnthonMS** [comment]
I am looking into adding all these features in the new my-slider-v2 card. Hopefully I get around to adding them before I run out of time to work on this again.

**Comment by storebatfar** [comment]
I love this card. Thank for creating it.
I would love to be able to show the slider value while sliding the slider.

**Comment by AnthonMS** [comment]
I have added this in the latest beta release. if setting config key showValue: true, then when sliding a bubble will appear above the thumb position and follow the thumb when sliding. This bubble shows the value of the slider.

If you wish to style the display for the value, you can do so by adding the styles key and adding the value key under it.
So an example of custom styling the value bubble could be:
```yaml
- type: custom:my-slider-v2
  entity: light.bathroom_spots
  showValue: true
  styles:
    value:
      - font-size: 16px
      - background: rgba(255,0,0,0.8)
      - color: white
```

Closing this issue as completed. Let me know if it still misbehaves.
Thank you for your patience. I'm sorry it has taken this long to get back to the further development of this card. Life got in the way.
