### ISSUE TITLE
Value/name on slider

### ISSUE THREAD

**Issue by MichalKurzewski** [AnthonMS/my-cards#5]
hello. slider was easy to implement. thank you
it could be nice if the value of the controlled entity could be displayed on the slider, for now i do it on a separate entity card which looks a bit off. 

cheers

M

**Comment by MichalKurzewski** [comment]
that is totally fine! thank you for reply! its not the MUST have - i love the way you can use the slider at the moment. good job so far!

**Comment by AnthonMS** [comment]
Added in v2.3.0-beta.1, out now.

There's a new label: option that renders text inside the slider:

```yaml
label: true                                  # the entity's friendly_name
label: Front Door Spots                      # any fixed text
label: '[[[ return entity.state + " %" ]]]'  # a template
```

That last (templated) form is the one you were after. It puts the live value on the slider and updates as the entity changes. It's pointer-events: none so it doesn't interfere with dragging, works alongside showValue, and you can restyle/reposition it with styles: label:. Give it a go and let me know if it does what you wanted.
