### ISSUE TITLE
[Bug]: Max does not work

### ISSUE THREAD

**Issue by briodan** [AnthonMS/my-cards#60]
### Current Behavior

when setting the max option in the card config, the card allows the value to be set higher then max value.

### Expected Behavior

when sliding up i expect the value to stop at what was set under the max setting.
in my case TV volume can not be set above 20.

### Steps To Reproduce

add the following card code

```
type: custom:my-slider-v2
entity: media_player.living_room_tv_2
vertical: true
styles:
  card:
    - height: 182px
    - width: 110px
  min: 1
  max: 20
  showMin: true
  disableScroll: true
layout_options:
  grid_columns: 1
  grid_rows: 3
```

slide volume and observe setting change on the device

### Environment

```markdown
- OS: HAOS 12.1
- Node:
- Version: current
- Hassio: 2024.9.3
```

**Comment by AnthonMS** [comment]
I haven't tested if it is because of this, but pretty sure it because you set the min and max in the styles. You need to put those config keys in the root of the slider config like so:

```yaml
type: custom:my-slider-v2
entity: media_player.living_room_tv_2
vertical: true
min: 1
max: 20
styles:
  card:
    - height: 182px
    - width: 110px
  showMin: true
  disableScroll: true
layout_options:
  grid_columns: 1
  grid_rows: 3
```

Let me know if this works so we can close the issue. If not, then I will try to find some time to look at it soon.

**Comment by Jonny-T-cyber** [comment]
Hi, this solution seems to work only if the card is in the "normal" yaml flow of the page.
But it no longer works if I open the card in a popup with browser_mod.
In this case, while maintaining the directions you gave, the max does not lock at the level set in the code.

I specify that this anomaly occurs only for the MAX value and not for the MIN...
**There is that a reason?**

_Off-topic:
I anticipate that there are other anomalies with "**my-card.js**" that you can already see in yellow color in the image I am about to provide you. For which I will open a specific issue. (I have verified that these additional anomalies always occur, even without using browser_mod)_

Anyway, returning to the topic, an error appears on the page and, moreover, in the console it reads:


```
connection-mixin.ts:156 Uncaught (in promise) 
{code: 'invalid_format', message: 'Invalid value for input_number.slider_intensity: 6.0 (range 1.0 - 5.0)'}
code
: 
"invalid_format"
message
: 
"Invalid value for input_number.slider_intensity: 6.0 (range 1.0 - 5.0)"
```

![image](https://github.com/user-attachments/assets/74b3f112-0e4e-4f7b-b164-d5f6cef18f65)




Thanks for the support

**Comment by AnthonMS** [comment]
The card behaves correctly here, the issue is the indentation in your config: `min`, `max`, and `showMin` are nested **inside the `styles:` block**, where they're ignored. They need to be at the card's top level:
```yaml
type: custom:my-slider-v2
entity: media_player.living_room_tv_2
vertical: true
min: 1
max: 20
showMin: true
disableScroll: true
styles:
  card:
    - height: 182px
    - width: 110px
```

With that, the slider maps the full track to volume 1–20 and can't set anything above 20. (I've added an automated test to make sure this keeps working.) 


Closing this issue. Comment if it still misbehaves with the corrected config.
Thank you for your patience. I'm sorry it has taken this long to get back to the further development of this card. Life got in the way.
