### ISSUE TITLE
[Feature]: slider-card templates

### ISSUE THREAD

**Issue by marcelvandorp** [AnthonMS/my-cards#66]
### Is your feature request related to a problem?

To visually set the requested charge levels, I created 24 vertical sliders, one for each hour of the day. This means I have to repeat the most part of each slider config, which is very inconvenient. And if a setting changes, I need to change that 24 times!

### Describe the solution you'd like

A solution as provided with the custom:button-card works great. I can define templates with all the common settings, and for each slider I only need to reference that template. In YAML it would look a bit like this:

At the top of the dashboard code (via 3-dot menu->raw editor):

```
my-slider-v2_templates:
  hour_slider:
    entity: input_number.wiwo_test_03
    allowTapping: true
    vertical: true
    showMin: false
    styles:
      card:
        - height: 150px
        - width: 15px
      track:
        - background: |
           [[[
             if (entity.state >= 0) return "orange";
             else return "blue";
           ]]]

```  
And each slider will become (only showing 2 of the 24):
```       
- type: custom:my-slider-v2
  entity: input_number.hour_00
  template: hour_slider
- type: custom:my-slider-v2
  entity: input_number.hour_01
  template: hour_slider
```

### Describe alternatives you've considered

The only way to achieve my goal was to repeat each slider-config 24 times.

### Additional context

This card is not meant to be useful on phones: the sliders are too narrow for that. I use this on a tablet, with a full-screen card. Above it is an apex chart with the hourly energy prices. The goal is to also add those 24 slider values to that chart (but that is not relevant to this FR)

**Comment by ChronoWerX82** [comment]
Is it working?

**Comment by AnthonMS** [comment]
Thanks for the detailed write-up, and sorry it took a while to circle back!

This is a real pain, and it's exactly what [decluttering-card](https://github.com/custom-cards/decluttering-card) is built for. It does precisely what you described (define a template once, reference it per card with variables), but generically for any custom card. So rather than build a second templating system inside my-slider-v2 that would just duplicate it, I'd point you there.

Your setup translates almost one-to-one. In the raw config (3-dot menu, Raw configuration editor):

```yaml
decluttering_templates:
  hour_slider:
    card:
      type: custom:my-slider-v2
      entity: '[[entity]]'
      allowTapping: true
      vertical: true
      showMin: false
      styles:
        card:
          - height: 150px
          - width: 15px
        track:
          - background: |
              [[[
                if (entity.state >= 0) return "orange";
                else return "blue";
              ]]]
```

And each of your 24 sliders becomes:

```yaml
- type: custom:decluttering-card
  template: hour_slider
  variables:
    - entity: input_number.hour_00
- type: custom:decluttering-card
  template: hour_slider
  variables:
    - entity: input_number.hour_01
```

Change the template once and all 24 update. Two things worth knowing:

- Only entity needs to be a variable. The [[[ ... ]]] track template keeps referring to entity, and my-slider-v2 resolves that to each card's own entity at render time, so you don't have to template it per slider. decluttering's [[entity]] and my-slider-v2's [[[ ]]] are different syntaxes and don't interfere here.
- If other settings need to differ per hour, add more variables the same way (with optional defaults in a default: block on the template).

Given decluttering-card handles this cleanly and is well maintained, I'm going to close this as wontfix rather than duplicate it. But it's a good suggestion, and this route should give you exactly the single-source-of-truth setup you were after. Thanks again!
