### ISSUE TITLE
[Feature]: Connecting sliders

### ISSUE THREAD

**Issue by marcelvandorp** [AnthonMS/my-cards#67]
### Is your feature request related to a problem?

I want 24 vertical sliders to set a charging level for a home battery, depending on the hourly prices. IT would be great that when I move slider 22, that slider 23 moves with it. The other way around: moving slider 23 will **not** move slider 22.
In the same manner, moving slider 21 will move slider 22, and ideally the movement of slider 22 also moves slider 23

### Describe the solution you'd like

I would like to be able to join sliders, and there are a few options with that too:

1. the slave of one master can be the master of another slave. Movement should be propagated down the chain
2. the value of the slave slider only follows the master slider **up**, when the master value will become **greater** than the slave
3. the value of the slave slider only follows the master slider **down** when the master value will become **smaller** than the slave
4. the slave for **up** movements can be different from the slave for **down**  movements. If it's the same, the slave **follows** the value of the master

### Additional context

I have an entity with attributes to control (actually, the attribute is an array with 24 slots). This also controls the charging/discharging level of the home battery. By putting this in vertical sliders below an APEX chart with hourly energy prices you can visually set the best strategy.
The table will also be plotted in the APEX chart for best representation (not yet implemented).

![Image](https://github.com/user-attachments/assets/6c05ae5e-8a95-438c-a612-e8b524340b3a)

**Comment by AnthonMS** [comment]
Thanks for the detailed rules, and for the screenshot, that makes the goal clear!

I'm going to close this as wontfix on the card side. The live "drag slider 22 and watch 23 move with it in real time" is a card-level interaction that's genuinely niche to build and maintain, and I'd rather not carry it long-term. But the practical result you're after (moving an earlier hour carries the later ones) is very achievable today with helper entities and one automation, and for setting a charge profile it works great.

The idea: one input_number per hour (hour_00 ... hour_23), create a my-slider-v2 for each, and add an automation that carries the change down the chain whenever a slider moves.

Automation (carries each hour into the next, propagating down the chain):

```yaml
alias: Battery hour sliders - carry down the chain
mode: queued
trigger:
  - platform: state
    entity_id:
      - input_number.hour_00
      - input_number.hour_01
      # ...
      - input_number.hour_23
condition:
  - "{{ trigger.from_state.state not in ['unknown','unavailable'] }}"
action:
  - variables:
      idx: "{{ trigger.entity_id.split('_')[-1] | int }}"
      next_entity: "input_number.hour_{{ '%02d' % (idx + 1) }}"
      prev: "{{ trigger.from_state.state | float }}"
      master: "{{ trigger.to_state.state | float }}"
      slave: "{{ states(next_entity) | float }}"
  - choose:
      # master moved UP past the next slider -> pull it up
      - conditions: "{{ master > prev and master > slave }}"
        sequence:
          - service: input_number.set_value
            target: { entity_id: "{{ next_entity }}" }
            data: { value: "{{ master }}" }
      # master moved DOWN past the next slider -> pull it down
      - conditions: "{{ master < prev and master < slave }}"
        sequence:
          - service: input_number.set_value
            target: { entity_id: "{{ next_entity }}" }
            data: { value: "{{ master }}" }
```

How it maps to your rules:

- Rule 1 (propagate down the chain): moving hour_21 sets hour_22, which re-triggers the automation and sets hour_23, and so on. `mode: queued` keeps it all in order.
- Rules 2 and 3 (follow up when the master crosses above, follow down when it crosses below): that's the two `choose` branches. If the master moves but doesn't cross the next slider, nothing happens.
- One-directional: hour_23 has no follower, and moving 23 never touches 22, exactly as you asked.

Two honest notes:

- If you set intermediate: true on the sliders, the value updates continuously while you drag (throttled, default every 100ms), so the follower sliders actually move during the drag, not just on release. It goes through HA (slider -> service -> automation -> set_value -> state), so there's a little latency, but it's effectively live. If a fast drag across many followers feels heavy, raise intermediateInterval a bit or leave intermediate off to update on release only.
- On your array attribute: the card can already read/write a scalar attribute (added in #48), but it doesn't yet index into a single slot of an array attribute, so it can't drive slot 22 of your 24-element array directly. That's why the 24 input_number helpers above are the route for now. Driving one array index from a slider is a small separate feature (it was part of this same idea) that I could add later if there's interest.

Hope this gets you the strategy-setting board you're after now rather than later!
